export enum UserVerificationCodeUseCaseEnum {
  PASSWORD_RESET = 'PASSWORD_RESET',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  EMAIL_UPDATE = 'EMAIL_UPDATE',
  SOCIAL_EMAIL_VERIFICATION = 'SOCIAL_EMAIL_VERIFICATION',
}
